import { PrismaClient, GuestFriendlyStatus, PriceRange } from '@prisma/client'

const prisma = new PrismaClient()

// Guest-friendly hotels in Pattaya with real data
const pattayaHotels = [
  // Beach Road Area - Budget
  {
    name: "Flipper House Hotel",
    area: "Beach Road",
    address: "520/1 Soi 8, Beach Road",
    latitude: 12.9341,
    longitude: 100.8831,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.BUDGET,
    distanceToBeach: 50,
    distanceToWalking: 800,
    distanceToSoi6: 1200,
    hasPool: true,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 7,
  },
  {
    name: "Sawasdee Siam",
    area: "Beach Road",
    address: "Beach Road Soi 10",
    latitude: 12.9355,
    longitude: 100.8835,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.BUDGET,
    distanceToBeach: 100,
    distanceToWalking: 600,
    distanceToSoi6: 1000,
    hasPool: true,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 6,
  },
  
  // Walking Street Area - Mid Range
  {
    name: "P72 Hotel",
    area: "Walking Street",
    address: "Near Walking Street entrance",
    latitude: 12.9258,
    longitude: 100.8739,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.MID,
    distanceToBeach: 200,
    distanceToWalking: 50,
    distanceToSoi6: 2000,
    hasPool: false,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 8,
  },
  {
    name: "Penthouse Hotel",
    area: "Walking Street",
    address: "Walking Street",
    latitude: 12.9262,
    longitude: 100.8741,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.MID,
    distanceToBeach: 100,
    distanceToWalking: 0,
    distanceToSoi6: 2100,
    hasPool: false,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 7,
  },

  // Soi 6 Area - Budget
  {
    name: "Areca Lodge",
    area: "Soi 6",
    address: "Soi 6/1",
    latitude: 12.9392,
    longitude: 100.8861,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.BUDGET,
    distanceToBeach: 150,
    distanceToWalking: 1300,
    distanceToSoi6: 0,
    hasPool: true,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 8,
  },
  {
    name: "Soi 6 Guest House",
    area: "Soi 6",
    address: "Soi 6",
    latitude: 12.9388,
    longitude: 100.8859,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.BUDGET,
    distanceToBeach: 100,
    distanceToWalking: 1250,
    distanceToSoi6: 0,
    hasPool: false,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 6,
  },

  // Second Road - Mid to High
  {
    name: "LK Metropole",
    area: "Second Road",
    address: "Soi Diana, Second Road",
    latitude: 12.9315,
    longitude: 100.8838,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.HIGH,
    distanceToBeach: 400,
    distanceToWalking: 900,
    distanceToSoi6: 800,
    hasPool: true,
    hasGym: true,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 9,
  },
  {
    name: "Sabai Resort",
    area: "Second Road",
    address: "Soi Sabai Resort, Second Road",
    latitude: 12.9298,
    longitude: 100.8812,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.MID,
    distanceToBeach: 500,
    distanceToWalking: 1000,
    distanceToSoi6: 900,
    hasPool: true,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 7,
  },

  // Hotels with Joiner Fees
  {
    name: "Hilton Pattaya",
    area: "Beach Road",
    address: "333/101 Beach Road",
    latitude: 12.9335,
    longitude: 100.8823,
    guestFriendly: GuestFriendlyStatus.JOINER_FEE,
    joinerFee: 1000,
    priceRange: PriceRange.LUXURY,
    distanceToBeach: 0,
    distanceToWalking: 700,
    distanceToSoi6: 1100,
    hasPool: true,
    hasGym: true,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 10,
  },
  {
    name: "Holiday Inn Pattaya",
    area: "Beach Road",
    address: "463/68 Beach Road",
    latitude: 12.9365,
    longitude: 100.8845,
    guestFriendly: GuestFriendlyStatus.JOINER_FEE,
    joinerFee: 500,
    priceRange: PriceRange.HIGH,
    distanceToBeach: 0,
    distanceToWalking: 500,
    distanceToSoi6: 900,
    hasPool: true,
    hasGym: true,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 9,
  },

  // NOT Guest Friendly
  {
    name: "Centara Grand Mirage",
    area: "North Pattaya",
    address: "277 Moo 5, Naklua",
    latitude: 12.9589,
    longitude: 100.8892,
    guestFriendly: GuestFriendlyStatus.NO,
    joinerFee: null,
    priceRange: PriceRange.LUXURY,
    distanceToBeach: 0,
    distanceToWalking: 3000,
    distanceToSoi6: 2000,
    hasPool: true,
    hasGym: true,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 10,
  },

  // More budget options popular with mongers
  {
    name: "Siam@Siam Design Hotel",
    area: "Second Road",
    address: "390 Moo 9, Second Road",
    latitude: 12.9352,
    longitude: 100.8852,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.MID,
    distanceToBeach: 300,
    distanceToWalking: 600,
    distanceToSoi6: 1000,
    hasPool: true,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 8,
  },
  {
    name: "The Classroom Hotel",
    area: "Second Road",
    address: "Soi 10, Second Road",
    latitude: 12.9341,
    longitude: 100.8842,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.MID,
    distanceToBeach: 400,
    distanceToWalking: 700,
    distanceToSoi6: 1100,
    hasPool: true,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 8,
  },
  {
    name: "March Hotel",
    area: "Soi Buakhao",
    address: "Soi Buakhao",
    latitude: 12.9325,
    longitude: 100.8798,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.BUDGET,
    distanceToBeach: 800,
    distanceToWalking: 1200,
    distanceToSoi6: 600,
    hasPool: true,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 7,
  },
  {
    name: "Bella Villa",
    area: "Soi Buakhao",
    address: "Soi Buakhao",
    latitude: 12.9318,
    longitude: 100.8795,
    guestFriendly: GuestFriendlyStatus.YES,
    joinerFee: null,
    priceRange: PriceRange.BUDGET,
    distanceToBeach: 850,
    distanceToWalking: 1300,
    distanceToSoi6: 650,
    hasPool: true,
    hasGym: false,
    hasSafe: true,
    nearbyATM: true,
    wifiQuality: 6,
  },
]

async function seedHotels() {
  console.log('🏨 Seeding guest-friendly hotel database...')
  
  for (const hotel of pattayaHotels) {
    await prisma.hotel.create({
      data: {
        ...hotel,
        city: 'pattaya',
      },
    })
    console.log(`✅ Added ${hotel.name} (${hotel.guestFriendly})`)
  }
  
  console.log(`✨ Successfully seeded ${pattayaHotels.length} hotels`)
}

seedHotels()
  .catch((e) => {
    console.error('Error seeding hotels:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })